Re-scope package names to `com.bluesmods` and remove dependency on xmlpull by copying it into this project. This is disruptive to consumers (mostly our own internal projects) but it is necessary. Android devices already have these classes (namely the xmlpull packages) on their classpath, and since this clashes with some built-in packages from OEMs, some devices will select the wrong one (from system framework / libart.jar) and this will cause crashes and unintended behavior, the main one being the limitTextBufferCapacity being missing causing a crash, such as:
`java.lang.NoSuchMethodError: No virtual method limitTextBufferCapacity(I)V in class Lorg/kxml2/io/KXmlParser; or its super classes (declaration of 'org.kxml2.io.KXmlParser' appears in /system/framework/core-libart.jar)
	at com.bluesmods.bluekikx.client.node.KikNodeInputStream.readNextStanza(KikNodeInputStream.java:47)``

In order to leave no confusion, changing the package names forces Android to always make the correct choice.